# language: node_js
# node_js:
#   - "10"
# cache:
#   directories:
#   - node_modules
# script:
#   - jest -c --collectCoverage

# jobs:
#   include:
#     - stage: Produce Coverage
#       node_js: node
#       script: npm install jest && jest -c --collectCoverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage




sudo: false
language: node_js
node_js:
- 'stable'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
# before_install:
# - npm update
install:
- yarn install
script:
- yarn test
- yarn run coveralls